package de.aicard.domains.enums;

/**
 * faculties for accounts and learnSets (FH)
 */
public enum Faculty {
    APPLIED_COMPUTER_SCIENCE,
    ARCHITECTURE,
    CIVIL_ENGINEERING,
    MANAGEMENT_AND_LEADERSHIP_IN_EARLY_CHILDHOOD_EDUCATION,
    BUSINESS_ADMINISTRATION,
    FORESTRY_AND_ECOSYSTEM_MANAGEMENT,
    HORTICULTURE,
    BUILDING_SERVICES_ENGINEERING,
    LANDSCAPE_ARCHITECTURE,
    EARLY_CHILDHOOD_EDUCATION,
    SOCIAL_WORK,
    URBAN_AND_SPATIAL_PLANNING_FOUNDATIONS,
    RAILWAY_ENGINEERING,
    ENERGY_ENGINEERING,
    TRAFFIC_TRANSPORTATION_AND_LOGISTICS_ENGINEERING
}